
server:
  port: 8081

jwt:
  secret: dlsjnfldjsnfdusnlasjnd123hbh3b2jh
  lifetime: 30m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Messenger
    username: postgres
    password: 1653
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update